apiVersion: apps/v1
kind: Deployment
metadata:
  name: knowledge-rag-webui-staging
  namespace: staging
  labels:
    app: knowledge-rag-webui-staging
    environment: staging
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: knowledge-rag-webui-staging
  template:
    metadata:
      labels:
        app: knowledge-rag-webui-staging
    spec:
      containers:
      - name: webui
        image: ghcr.io/anubissbe/knowledge-rag-webui:develop
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          value: "staging"
        - name: VITE_API_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: webui-staging-config
              key: api-base-url
        - name: VITE_KNOWLEDGE_GRAPH_URL
          valueFrom:
            configMapKeyRef:
              name: webui-staging-config
              key: knowledge-graph-url
        - name: VITE_VECTOR_DB_URL
          valueFrom:
            configMapKeyRef:
              name: webui-staging-config
              key: vector-db-url
        - name: VITE_UNIFIED_DB_URL
          valueFrom:
            configMapKeyRef:
              name: webui-staging-config
              key: unified-db-url
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: knowledge-rag-webui-staging-service
  namespace: staging
  labels:
    app: knowledge-rag-webui-staging
spec:
  selector:
    app: knowledge-rag-webui-staging
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: webui-staging-config
  namespace: staging
data:
  api-base-url: "https://staging-api.knowledge-rag.example.com"
  knowledge-graph-url: "https://staging-graph.knowledge-rag.example.com"
  vector-db-url: "https://staging-vector.knowledge-rag.example.com"
  unified-db-url: "https://staging-db.knowledge-rag.example.com"