apiVersion: apps/v1
kind: Deployment
metadata:
  name: knowledge-rag-webui
  namespace: production
  labels:
    app: knowledge-rag-webui
    version: v1.0.0
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: knowledge-rag-webui
  template:
    metadata:
      labels:
        app: knowledge-rag-webui
    spec:
      containers:
      - name: webui
        image: ghcr.io/anubissbe/knowledge-rag-webui:latest
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: VITE_API_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: webui-config
              key: api-base-url
        - name: VITE_KNOWLEDGE_GRAPH_URL
          valueFrom:
            configMapKeyRef:
              name: webui-config
              key: knowledge-graph-url
        - name: VITE_VECTOR_DB_URL
          valueFrom:
            configMapKeyRef:
              name: webui-config
              key: vector-db-url
        - name: VITE_UNIFIED_DB_URL
          valueFrom:
            configMapKeyRef:
              name: webui-config
              key: unified-db-url
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
      securityContext:
        fsGroup: 1000
---
apiVersion: v1
kind: Service
metadata:
  name: knowledge-rag-webui-service
  namespace: production
  labels:
    app: knowledge-rag-webui
spec:
  selector:
    app: knowledge-rag-webui
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: webui-config
  namespace: production
data:
  api-base-url: "https://api.knowledge-rag.example.com"
  knowledge-graph-url: "https://graph.knowledge-rag.example.com"
  vector-db-url: "https://vector.knowledge-rag.example.com"
  unified-db-url: "https://db.knowledge-rag.example.com"